### ISSUE TITLE
Rotation only works for local player

### ISSUE THREAD

**Issue by Assambra** [vu-luong/ezy-smashers#47] opened 2023-06-04 18:30 UTC
The Rotation of the local player works but not for remote players.

**Comment by vu-luong** [comment] 2023-06-05 02:42
Thanks for raising the issue. It was caused by Unity new version changes the values of x, y, z in Quaternion. Now we need to use x, y, z in Quaternion.eulerAngles instead.

The issue was fixed in https://github.com/vu-luong/ezy-smashers/pull/48.

@Assambra Could you check again?

**Comment by Assambra** [comment] 2023-06-05 06:56
Your fix work, thank you.

**Closed** 2023-06-05 10:06 UTC
Labels: bug
